### ISSUE TITLE
How do you get this to work? 

### ISSUE THREAD

**Issue by Strutsagget** [mgoldsborough/google-play-in-app-billing-verification#1]
Hi is there an update to the sample code as it dosnt seem to be updated.

**Comment by mgoldsborough** [comment]
This is a somewhat old repo.  I believe the Google Play API has changed since I was developing this.  I'm not sure if it will still work.  It was supposed to provide you a way to validate market purchases on your own server in order to perform some post-purchase action.

**Comment by mitchobrian** [comment]
Yes, it changed a bit. Could you transform you lib to the v3 of the Google API?
http://developer.android.com/google/play/billing/api.html
It's mainly the JSON structure which changed to:
'{ 
   "orderId":"12999763169054705758.1371079406387615", 
   "packageName":"com.example.app",
   "productId":"exampleSku",
   "purchaseTime":1345678900000,
   "purchaseState":0,
   "developerPayload":"bGoa+V7g/yqDXvKRqq+JTFn4uQZbPiQJo4pf9RzJ",
   "purchaseToken":"rojeslcdyyiapnqcynkjyyjh"
 }'

**Comment by ragcsalo** [comment]
Can you update it according to mitchobrian's comment? :-)

**Comment by mitchobrian** [comment]
@ragcsalo check out my fork https://github.com/mitchobrian/google-play-in-app-billing-verification

**Comment by ragcsalo** [comment]
Thanks!!!! I will test it today..... :-)

**Comment by ragcsalo** [comment]
I'm testing subscriptions... and in the response JSON I don't get the "orderId" and the "developerPayload". Is it normal? Maybe I can't verify test purchases, only real ones?

**Comment by mitchobrian** [comment]
normally u should get it

**Comment by ragcsalo** [comment]
So I've made a live subscription (not test), and now I get the orderId. :-) But the developerPayload is still missing... If I insert it with a custom value, and click on the Validate button, I get the error message: "There was an error in your given parameters.". Is the developerPayload really important? Or something else went wrong?

My JSON response from Google is the following:

{"orderId":"12999763169054705758.1322704963951359","packageName":"com.benkesmith.magic_apps","productId":"magic_apps_by_benke_smith","purchaseTime":1430414316492,"purchaseState":0,"purchaseToken":"hkgckclilabailmdakmafkbn.AO-J1OyrG0-ZG_8xVCl8JBHq6-QVVNAxi1SU24JsyIZN-6d-vKScZDL_a2NNAcERME2A55Voh4N_resGappzA8VDm9_b8RZQZKplxrTh3uABkv7HfkArrJ5Q3d43sVdBxHJp4ptP5aTRk_lwNXGcvICvjkTOJxkmfA","autoRenewing":true}

**Comment by ragcsalo** [comment]
Finally I tried this: https://gist.github.com/prime31/4750744
And it's working fine!!! :-))))

**Comment by mitchobrian** [comment]
Sorry for my delay, I was busy a bit. Is there a mistake in my code? 
Works still fine 4 me!

**Comment by ragcsalo** [comment]
You should'nt check for property names (eg. orderId) in the transaction Json data, because they can vary. For example,  for test subscriptions there is no orderId... I think you should'nt check the transaction data at all, just pass it for verification. :-)
